"""chat models

Revision ID: 83216b0fd7a6
Revises: e85ce6e9f4fb
Create Date: 2025-08-25 08:12:35.511705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83216b0fd7a6'
down_revision = 'e85ce6e9f4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ban_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ban_user_id'), ['user_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moderator', sa.Boolean(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('is_moderator')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_room_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('ban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_user_id'))
        batch_op.drop_index(batch_op.f('ix_ban_room_id'))
        batch_op.drop_index(batch_op.f('ix_ban_created_at'))

    op.drop_table('ban')
    op.drop_table('room')
    # ### end Alembic commands ###
